sqlite3mem: &SQLITE3MEM
  adapter: sqlite3
  database: ":memory:"

sqlite3: &SQLITE
  adapter: sqlite3
  database: audited_test.sqlite3.db

postgresql: &POSTGRES
  adapter: postgresql
  username: postgres
  password:
  database: audited_test
  min_messages: ERROR

mysql: &MYSQL
  adapter: mysql2
  host: localhost
  username: root
  password:
  database: audited_test

test:
  <<: *<%= ENV['DB'] || 'SQLITE3MEM' %>
